prompt --application/pages/page_00005
begin
--   Manifest
--     PAGE: 00005
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.0'
,p_default_workspace_id=>1600476898799620
,p_default_application_id=>101
,p_default_id_offset=>0
,p_default_owner=>'PAY'
);
wwv_flow_imp_page.create_page(
 p_id=>5
,p_name=>'AI CHATBOT'
,p_alias=>'AI-CHATBOT'
,p_step_title=>'AI CHATBOT'
,p_autocomplete_on_off=>'OFF'
,p_javascript_code=>wwv_flow_string.join(wwv_flow_t_varchar2(
'',
'// ================================================================',
'// IMPORTANT: Apna FastAPI server URL yahan set karo',
'// ================================================================',
'var AI_CHAT_API_URL = "http://10.0.10.51:8000/ai/chat";',
' ',
'function aiChatApiOrigin() {',
'    return AI_CHAT_API_URL.replace(/\/ai\/chat$/, "");',
'}',
' ',
'// Pichli baar jo email/phone use kiya tha, yaad rakhta hai (sirf is',
unistr('// browser session ke liye \2014 page reload pe reset ho jata hai)'),
'var aiChatLastEmail = "";',
'var aiChatLastPhone = "";',
' ',
' ',
'// ================================================================',
unistr('// CHAT HISTORY \2014 pichli baatein AI ko yaad rakhne ke liye'),
'// ================================================================',
'var aiChatHistory = [];',
' ',
' ',
'// ================================================================',
'// BUBBLE HELPERS',
'// ================================================================',
'function aiChatAppendBubble(text, type) {',
'    var $window = $("#ai-chat-window");',
'    var $bubble = $("<div>").addClass("ai-chat-bubble " + type).text(text);',
'    $window.append($bubble);',
'    $window.scrollTop($window[0].scrollHeight);',
'    return $bubble;',
'}',
' ',
'function aiChatAppendDownloadLink($bubble, downloadUrl, fileName) {',
'    var fullUrl = aiChatApiOrigin() + downloadUrl;',
'    var $link = $("<a>")',
'        .addClass("download-link")',
'        .attr("href", fullUrl)',
'        .attr("target", "_blank")',
'        .attr("download", fileName)',
'        .text("Download: " + fileName);',
'    $bubble.append($("<br>")).append($link);',
'}',
' ',
'// Bot ke jawab ke neeche Speak / Email / WhatsApp buttons banata hai.',
'// answerText = jo bolna/bhejna hai, downloadUrl/fileName = agar file bani ho',
'function aiChatAppendActions(answerText, downloadUrl, fileName) {',
'    var $window = $("#ai-chat-window");',
'    var $actions = $("<div>").addClass("ai-chat-actions");',
' ',
unistr('    var $speakBtn = $("<button>").addClass("ai-chat-action-btn").attr("type", "button").text("\D83D\DD0A Speak");'),
'    $speakBtn.on("click", function () { aiChatSpeak(answerText); });',
' ',
unistr('    var $emailBtn = $("<button>").addClass("ai-chat-action-btn").attr("type", "button").text("\D83D\DCE7 Email");'),
'    $emailBtn.on("click", function () { aiChatSendEmailFor(answerText, fileName); });',
' ',
unistr('    var $waBtn = $("<button>").addClass("ai-chat-action-btn").attr("type", "button").text("\D83D\DCAC WhatsApp");'),
'    $waBtn.on("click", function () { aiChatSendWhatsAppFor(answerText, downloadUrl); });',
' ',
'    $actions.append($speakBtn).append($emailBtn).append($waBtn);',
'    $window.append($actions);',
'    $window.scrollTop($window[0].scrollHeight);',
'}',
' ',
'function aiChatShowTyping() {',
'    var $window = $("#ai-chat-window");',
'    var $typing = $("<div>").addClass("ai-chat-typing").attr("id", "ai-chat-typing-indicator").text("AI type kar raha hai...");',
'    $window.append($typing);',
'    $window.scrollTop($window[0].scrollHeight);',
'}',
' ',
'function aiChatHideTyping() {',
'    $("#ai-chat-typing-indicator").remove();',
'}',
' ',
' ',
'// ================================================================',
unistr('// VOICE OUTPUT \2014 jawab ko bol kar sunana (built-in browser feature,'),
'// koi extra setup ya API key nahi chahiye)',
'// ================================================================',
'function aiChatSpeak(text) {',
'    if (!("speechSynthesis" in window)) {',
'        alert("Ye browser voice output support nahi karta.");',
'        return;',
'    }',
'    window.speechSynthesis.cancel(); // pehle se koi bol raha ho to rok do',
'    var utterance = new SpeechSynthesisUtterance(text);',
unistr('    utterance.lang = "ur-PK"; // Urdu \2014 agar na chale to browser khud English try karega'),
'    utterance.rate = 1;',
'    window.speechSynthesis.speak(utterance);',
'}',
' ',
' ',
'// ================================================================',
unistr('// EMAIL / WHATSAPP \2014 kisi bhi (purane ya naye) jawab ko bhejna'),
'// ================================================================',
'function aiChatSendEmailFor(answerText, fileName) {',
'    var email = prompt("Email address likhein:", aiChatLastEmail);',
'    if (!email) return;',
'    aiChatLastEmail = email;',
' ',
'    var payload = { to: email, subject: "AI ERP Report", body: answerText };',
'    if (fileName) {',
'        payload.file_name = fileName;',
'    }',
' ',
'    $.ajax({',
'        url: aiChatApiOrigin() + "/send/email",',
'        method: "POST",',
'        contentType: "application/json",',
'        data: JSON.stringify(payload),',
'        timeout: 30000',
'    })',
'    .done(function (response) {',
'        var type = (response.status === "success") ? "bot" : "error";',
'        aiChatAppendBubble(response.message || "Email process ho gaya.", type);',
'    })',
'    .fail(function () {',
'        aiChatAppendBubble("Email bhejne mein connection error aayi.", "error");',
'    });',
'}',
' ',
'function aiChatSendWhatsAppFor(answerText, downloadUrl) {',
'    var phone = prompt("WhatsApp number likhein (country code ke sath, e.g. 923001234567):", aiChatLastPhone);',
'    if (!phone) return;',
'    aiChatLastPhone = phone;',
' ',
'    var payload = { message: answerText, phone: phone };',
'    if (downloadUrl) {',
'        payload.download_url = aiChatApiOrigin() + downloadUrl;',
'    }',
' ',
'    $.ajax({',
'        url: aiChatApiOrigin() + "/send/whatsapp",',
'        method: "POST",',
'        contentType: "application/json",',
'        data: JSON.stringify(payload),',
'        timeout: 30000',
'    })',
'    .done(function (response) {',
'        var type = (response.status === "success") ? "bot" : "error";',
'        aiChatAppendBubble(response.message || "WhatsApp process ho gaya.", type);',
'    })',
'    .fail(function () {',
'        aiChatAppendBubble("WhatsApp bhejne mein connection error aayi.", "error");',
'    });',
'}',
' ',
' ',
'// ================================================================',
'// MAIN SEND FUNCTION',
'// ================================================================',
'function aiChatSendMessage() {',
'    var $input = $("#ai-chat-input");',
'    var $sendBtn = $("#ai-chat-send-btn");',
'    var question = $input.val().trim();',
' ',
'    if (!question) {',
'        return;',
'    }',
' ',
'    var exportFormat = null;',
'    if ($("#ai-chat-export-excel").is(":checked")) {',
'        exportFormat = "excel";',
'    } else if ($("#ai-chat-export-pdf").is(":checked")) {',
'        exportFormat = "pdf";',
'    }',
' ',
'    aiChatAppendBubble(question, "user");',
'    $input.val("");',
'    $sendBtn.prop("disabled", true);',
'    aiChatShowTyping();',
' ',
'    var payload = { question: question, history: aiChatHistory };',
'    if (exportFormat) {',
'        payload.export_format = exportFormat;',
'    }',
' ',
'    $.ajax({',
'        url: AI_CHAT_API_URL,',
'        method: "POST",',
'        contentType: "application/json",',
'        data: JSON.stringify(payload),',
'        timeout: 60000',
'    })',
'    .done(function (response) {',
'        aiChatHideTyping();',
' ',
'        var bubbleType = (response.status === "success") ? "bot" : "error";',
'        var answerText = response.answer || "Koi jawab nahi mila.";',
'        aiChatAppendBubble(answerText, bubbleType);',
' ',
'        // Agar file bani hai, download link dikhao (last bubble ke andar)',
'        if (response.download_url) {',
'            var $lastBubble = $("#ai-chat-window .ai-chat-bubble").last();',
'            aiChatAppendDownloadLink($lastBubble, response.download_url, response.file_name);',
'        }',
' ',
'        if (response.export_error) {',
'            aiChatAppendBubble("Export error: " + response.export_error, "error");',
'        }',
' ',
'        // Sirf successful bot jawab ke neeche Speak/Email/WhatsApp buttons dikhao',
'        if (bubbleType === "bot") {',
'            aiChatAppendActions(answerText, response.download_url || null, response.file_name || null);',
'        }',
' ',
unistr('        // History update \2014 agli baar AI ko context milega'),
'        if (response.status === "success") {',
'            aiChatHistory.push({ role: "user", content: question });',
'            aiChatHistory.push({ role: "assistant", content: answerText });',
'            if (aiChatHistory.length > 30) {',
'                aiChatHistory = aiChatHistory.slice(-30);',
'            }',
'        }',
'    })',
'    .fail(function (xhr, status, error) {',
'        aiChatHideTyping();',
'        var msg = "Connection error: server se jawab nahi mila. (" + (xhr.status || status) + ")";',
'        aiChatAppendBubble(msg, "error");',
'        console.error("AI Chat error:", status, error, xhr.responseText);',
'    })',
'    .always(function () {',
'        $sendBtn.prop("disabled", false);',
'        $input.trigger("focus");',
'    });',
'}',
' ',
' ',
'// ================================================================',
unistr('// VOICE INPUT (mic button) \2014 Chrome/Edge mein kaam karta hai.'),
'// Firefox mein ye feature browser support nahi karta.',
'// ================================================================',
'var aiChatRecognition = null;',
'var aiChatIsRecording = false;',
' ',
'function aiChatInitVoiceInput() {',
'    var SpeechRecognitionApi = window.SpeechRecognition || window.webkitSpeechRecognition;',
'    if (!SpeechRecognitionApi) {',
unistr('        $("#ai-chat-mic-btn").hide(); // is browser mein support nahi \2014 button hi chhupa do'),
'        return;',
'    }',
' ',
'    aiChatRecognition = new SpeechRecognitionApi();',
'    aiChatRecognition.lang = "ur-PK";',
'    aiChatRecognition.continuous = false;',
'    aiChatRecognition.interimResults = false;',
' ',
'    aiChatRecognition.onresult = function (event) {',
'        var transcript = event.results[0][0].transcript;',
'        $("#ai-chat-input").val(transcript);',
'    };',
' ',
'    aiChatRecognition.onerror = function () {',
'        $("#ai-chat-mic-btn").removeClass("recording");',
'        aiChatIsRecording = false;',
'    };',
' ',
'    aiChatRecognition.onend = function () {',
'        $("#ai-chat-mic-btn").removeClass("recording");',
'        aiChatIsRecording = false;',
'    };',
'}',
' ',
'function aiChatToggleVoiceInput() {',
'    if (!aiChatRecognition) return;',
' ',
'    if (aiChatIsRecording) {',
'        aiChatRecognition.stop();',
'        aiChatIsRecording = false;',
'        $("#ai-chat-mic-btn").removeClass("recording");',
'    } else {',
'        aiChatRecognition.start();',
'        aiChatIsRecording = true;',
'        $("#ai-chat-mic-btn").addClass("recording");',
'    }',
'}',
' ',
' ',
'// ================================================================',
unistr('// EVENT BINDINGS \2014 page load hote hi ye sab activate ho jate hain'),
'// ================================================================',
'$(function () {',
'    aiChatInitVoiceInput();',
' ',
'    // Enter key se message bhejna',
'    $(document).on("keypress", "#ai-chat-input", function (e) {',
'        if (e.which === 13 || e.keyCode === 13) {',
'            e.preventDefault();',
'            aiChatSendMessage();',
'        }',
'    });',
' ',
'    // Mic button click',
'    $(document).on("click", "#ai-chat-mic-btn", function () {',
'        aiChatToggleVoiceInput();',
'    });',
'});',
' '))
,p_page_template_options=>'#DEFAULT#'
,p_protection_level=>'C'
,p_page_component_map=>'11'
);
wwv_flow_imp_page.create_page_plug(
 p_id=>wwv_flow_imp.id(1631212593026724)
,p_plug_name=>'ERP AI CHATBOT'
,p_title=>'ERP AI CHATBOT'
,p_region_template_options=>'#DEFAULT#:t-Region--scrollBody'
,p_plug_template=>4072358936313175081
,p_plug_display_sequence=>10
,p_location=>null
,p_plug_source=>wwv_flow_string.join(wwv_flow_t_varchar2(
' ',
'<div id="ai-chat-container">',
'    <div id="ai-chat-window"></div>',
' ',
'    <div id="ai-chat-input-row">',
'        <input type="text" id="ai-chat-input" placeholder="Apna sawal likhein ya mic dabayein..." autocomplete="off">',
unistr('        <button id="ai-chat-mic-btn" type="button" title="Bol kar likhein">\D83C\DFA4</button>'),
'        <button id="ai-chat-send-btn" type="button">Send</button>',
'    </div>',
' ',
'    <div id="ai-chat-export-row">',
'        <label>',
'            <input type="checkbox" id="ai-chat-export-excel"> Excel file bhi banao',
'        </label>',
'        <label>',
'            <input type="checkbox" id="ai-chat-export-pdf"> PDF file bhi banao',
'        </label>',
'    </div>',
'</div>',
' ',
'<style>',
'#ai-chat-container {',
'    max-width: 700px;',
'    margin: 0 auto;',
'    border: 1px solid #d9d9d9;',
'    border-radius: 10px;',
'    overflow: hidden;',
'    font-family: -apple-system, "Segoe UI", Arial, sans-serif;',
'    background: #fff;',
'}',
' ',
'#ai-chat-window {',
'    height: 420px;',
'    overflow-y: auto;',
'    padding: 16px;',
'    background: #f7f8fa;',
'}',
' ',
'.ai-chat-bubble {',
'    max-width: 80%;',
'    padding: 10px 14px;',
'    border-radius: 14px;',
'    margin-bottom: 4px;',
'    line-height: 1.4;',
'    font-size: 14px;',
'    white-space: pre-wrap;',
'    word-wrap: break-word;',
'}',
' ',
'.ai-chat-bubble.user {',
'    background: #1F4E78;',
'    color: #fff;',
'    margin-left: auto;',
'    border-bottom-right-radius: 4px;',
'}',
' ',
'.ai-chat-bubble.bot {',
'    background: #eaeaea;',
'    color: #222;',
'    margin-right: auto;',
'    border-bottom-left-radius: 4px;',
'}',
' ',
'.ai-chat-bubble.error {',
'    background: #fdecea;',
'    color: #a3231f;',
'    margin-right: auto;',
'    border: 1px solid #f5c2c0;',
'}',
' ',
'.ai-chat-bubble .download-link {',
'    display: inline-block;',
'    margin-top: 8px;',
'    padding: 6px 12px;',
'    background: #1F4E78;',
'    color: #fff !important;',
'    text-decoration: none;',
'    border-radius: 6px;',
'    font-size: 13px;',
'}',
' ',
'.ai-chat-bubble .download-link:hover {',
'    background: #163a5c;',
'}',
' ',
'.ai-chat-typing {',
'    color: #888;',
'    font-style: italic;',
'    font-size: 13px;',
'    margin-bottom: 10px;',
'}',
' ',
'/* Bot bubble ke neeche action buttons (Speak / Email / WhatsApp) */',
'.ai-chat-actions {',
'    display: flex;',
'    gap: 6px;',
'    margin-bottom: 12px;',
'    margin-right: auto;',
'    max-width: 80%;',
'}',
' ',
'.ai-chat-action-btn {',
'    background: #fff;',
'    border: 1px solid #ccc;',
'    border-radius: 12px;',
'    padding: 3px 10px;',
'    font-size: 12px;',
'    cursor: pointer;',
'    color: #444;',
'}',
' ',
'.ai-chat-action-btn:hover {',
'    background: #f0f0f0;',
'    border-color: #1F4E78;',
'}',
' ',
'#ai-chat-input-row {',
'    display: flex;',
'    gap: 8px;',
'    padding: 12px;',
'    border-top: 1px solid #e5e5e5;',
'    background: #fff;',
'}',
' ',
'#ai-chat-input {',
'    flex: 1;',
'    padding: 10px 12px;',
'    border: 1px solid #ccc;',
'    border-radius: 20px;',
'    font-size: 14px;',
'    outline: none;',
'}',
' ',
'#ai-chat-input:focus {',
'    border-color: #1F4E78;',
'}',
' ',
'#ai-chat-mic-btn {',
'    padding: 10px 14px;',
'    background: #fff;',
'    border: 1px solid #ccc;',
'    border-radius: 50%;',
'    cursor: pointer;',
'    font-size: 16px;',
'}',
' ',
'#ai-chat-mic-btn:hover {',
'    background: #f0f0f0;',
'}',
' ',
'#ai-chat-mic-btn.recording {',
'    background: #d9534f;',
'    border-color: #d9534f;',
'}',
' ',
'#ai-chat-send-btn {',
'    padding: 10px 20px;',
'    background: #1F4E78;',
'    color: #fff;',
'    border: none;',
'    border-radius: 20px;',
'    cursor: pointer;',
'    font-size: 14px;',
'}',
' ',
'#ai-chat-send-btn:hover {',
'    background: #163a5c;',
'}',
' ',
'#ai-chat-send-btn:disabled {',
'    background: #999;',
'    cursor: not-allowed;',
'}',
' ',
'#ai-chat-export-row {',
'    padding: 6px 16px 10px;',
'    font-size: 13px;',
'    color: #555;',
'    background: #fff;',
'    display: flex;',
'    gap: 16px;',
'}',
'</style>',
' ',
' '))
,p_attributes=>wwv_flow_t_plugin_attributes(wwv_flow_t_varchar2(
  'expand_shortcuts', 'N',
  'output_as', 'HTML')).to_clob
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(1631306233026725)
,p_name=>'Chat Send Click'
,p_event_sequence=>10
,p_triggering_element_type=>'JQUERY_SELECTOR'
,p_triggering_element=>'#ai-chat-send-btn'
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'click'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(1631417782026726)
,p_event_id=>wwv_flow_imp.id(1631306233026725)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'aiChatSendMessage();'
);
wwv_flow_imp_page.create_page_da_event(
 p_id=>wwv_flow_imp.id(1631566041026727)
,p_name=>'Chat Enter Key'
,p_event_sequence=>20
,p_triggering_element_type=>'JQUERY_SELECTOR'
,p_triggering_element=>'#ai-chat-input'
,p_bind_type=>'bind'
,p_execution_type=>'IMMEDIATE'
,p_bind_event_type=>'keypress'
,p_display_when_type=>'NEVER'
);
wwv_flow_imp_page.create_page_da_action(
 p_id=>wwv_flow_imp.id(1631657097026728)
,p_event_id=>wwv_flow_imp.id(1631566041026727)
,p_event_result=>'TRUE'
,p_action_sequence=>10
,p_execute_on_page_init=>'N'
,p_action=>'NATIVE_JAVASCRIPT_CODE'
,p_attribute_01=>'aiChatSendMessage();'
,p_server_condition_type=>'NEVER'
);
wwv_flow_imp.component_end;
end;
/
